version: '3.3'

services:
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - api

