name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U pip setuptools wheel cymem numpy
        python -m pip install sudachipy sudachidict_core mecab-python3 unidic-lite
        python setup.py install

    - name: Test with unittest
      run: |
        python -m unittest discover tests
